In [1]:
import numpy as np

In [2]:
number_students = int(input("enter number of sutdents:"))
number_subjects = int(input("enter number of subjects:"))
print(number_students)
print(number_subjects)

enter number of sutdents:3
enter number of subjects:2
3
2


In [3]:
myarray= np.zeros((number_students,number_subjects))
print(myarray)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [4]:
for i in range(0, number_students):
    for j in range(number_subjects):
        myarray[i, j]=int(input(f"Student {i} - subject {j}\nenter mark:"))

Student 0 - subject 0
enter mark:10
Student 0 - subject 1
enter mark:14
Student 1 - subject 0
enter mark:6
Student 1 - subject 1
enter mark:7
Student 2 - subject 0
enter mark:18
Student 2 - subject 1
enter mark:19


In [5]:
myarray

array([[10., 14.],
       [ 6.,  7.],
       [18., 19.]])

In [10]:
total = myarray.sum(axis=1)
total

array([24., 13., 37.])

In [12]:
percentage = (total / (number_subjects * 20)) * 100
percentage

array([60. , 32.5, 92.5])

In [48]:
percentage = np.array([60., 57, 32.5, 72, 86, 92.5])

grades = np.zeros_like(percentage, dtype=object)
grades

grade_dict = {
    "A+": 90,
    "A": 80,
    "B+": 70,
    "B": 60,
    "C": 50,
}

for gr, p in grade_dict.items():
    grades[(percentage >= p) & (grades == 0)] = gr
    
grades[(grades == 0)] = 'F'
grades

array(['B', 'C', 'F', 'B+', 'A', 'A+'], dtype=object)